module.exports = {
  es: {
    // General
    appearance: 'Apariencia e Idioma',
    theme: 'Tema',
    darkMode: 'Oscuro',
    lightMode: 'Claro',
    language: 'Idioma',
    settings: 'Ajustes',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    loading: 'Cargando...',
    success: 'Guardado correctamente',
    error: 'Ocurrió un error',
    // Navegación
    navHome: 'Inicio',
    navBarbers: 'Barberos',
    navPanel: 'Panel',
    navSettings: 'Ajustes',
    // Ajustes — secciones
    myBarberShop: 'Mi Barbería',
    administration: 'Administración',
    configNameLogo: 'Configurar Nombre y Logo',
    managePartners: 'Gestionar Socios',
    securityAccess: 'Seguridad y Acceso',
    currencyCommission: 'Moneda y Comisión Bancaria',
    manageBarbers: 'Gestionar Barberos',
    manageServices: 'Gestionar Servicios y Productos',
    cashFund: 'Fondo de Caja (Cambio)',
    // Botones comunes
    add: 'Agregar',
    edit: 'Editar',
    delete: 'Eliminar',
    activate: 'Activar',
    pause: 'Pausar',
    saveChanges: 'Guardar Cambios',
    addNew: 'Agregar Nuevo',
    // ScreenInicio
    registerSale: 'Registrar Venta',
    advancePayment: 'Adelanto / Pago',
    cashAudit: 'Arqueo / Cerrar Caja del Día',
    quickRegister: 'Registro Rápido',
    todaySales: 'Ventas del Día',
    monthClosed: 'El mes está cerrado. Reabrilo en el Panel para agregar registros.',
    // Modales
    registerSaleTitle: 'Registrar Venta',
    registerExpenseTitle: 'Registrar Gasto',
    advanceTitle: 'Adelanto / Pago',
    cashAuditTitle: 'Arqueo de Caja',
    // ScreenAjustes — secciones principales
    myBarberShopSection: 'Mi Barbería',
    administrationSection: 'Administración',
    configNameLogoBtn: 'Configurar Nombre y Logo',
    manageSociosBtn: 'Gestionar Socios',
    securityAccessBtn: 'Seguridad y Acceso',
    currencyCommissionBtn: 'Moneda y Comisión Bancaria',
    manageBarbersBtn: 'Gestionar Barberos',
    manageServicesBtn: 'Gestionar Servicios y Productos',
    cashFundBtn: 'Fondo de Caja (Cambio)',
    // ScreenInicio — cabeceras y etiquetas
    filterDate: 'Filtrando por fecha',
    today: 'Hoy',
    totalSales: 'Total Ventas',
    cash: 'Efectivo',
    bank: 'Banco',
    bankCommission: 'Comisión Bancaria',
    barberCommissions: 'Comisiones Barberos',
    partnerPayments: 'Pagos Socios',
    netBalance: 'Saldo Neto',
    cashInBox: 'Efectivo en Caja',
    cashFundLabel: 'Fondo de Caja',
    expenses: 'Gastos',
    noSalesDay: 'Sin ventas este día',
    // Meses
    month_0: 'Enero', month_1: 'Febrero', month_2: 'Marzo', month_3: 'Abril',
    month_4: 'Mayo', month_5: 'Junio', month_6: 'Julio', month_7: 'Agosto',
    month_8: 'Septiembre', month_9: 'Octubre', month_10: 'Noviembre', month_11: 'Diciembre',
    // ScreenBarberos
    barbersTitle: 'Barberos',
    currentMonth: 'En curso',
    goToCurrentMonth: '📅 Ir al mes actual',
    noActiveBarbers: 'No hay barberos activos',
    noActivityMonth: 'Sin actividad en',
    active: '● Activo',
    inactive: '● Inactivo',
    generated: 'Generado (mes)',
    grossCommission: 'Comisión Bruta',
    advancesPaid: 'Adelantos cobrados',
    netBalance2: 'Saldo neto',
    commissionGenMinusAdv: 'Comisión generada menos adelantos cobrados',
    advanceExceedsComm: 'Adelanto menos comisión generada',
    canStillCollect: '✓ Aún puede cobrar',
    advanceExceedsBy: '⚠️ El adelanto supera la comisión en',
    zeroBalance: '✓ Saldo cero',
    advanceHistory: '💸 Historial de Adelantos / Pagos',
    noAdvancesMonth: 'No se han registrado Adelantos este mes.',
    productsNoBenefit: 'Las ventas de productos no generan comisión — van 100% a la barbería',
    newBarber: 'Nuevo Barbero',
    barberAdded: '¡Barbero agregado!',
    fullName: 'Nombre Completo',
    serviceCommission: 'Comisión por Servicios',
    addBarber: 'Agregar Barbero',
    servicesProducts: 'Servicios & Productos',
    services: 'Servicios',
    products: 'Productos',
    noServicesYet: 'No hay servicios aún',
    noProductsYet: 'No hay productos aún',
    addService: 'Agregar servicio',
    addProduct: 'Agregar producto',
    serviceName: 'Nombre del servicio',
    productName: 'Nombre del producto',
    currentStock: 'Stock actual',
    minStock: 'Stock mínimo',
    added: '✓ Agregado',
    // ScreenPanel
    panelTitle: 'Panel',
    inProgress: '· En curso',
    monthClosed2: 'Mes cerrado — datos bloqueados',
    reopenMonth: 'Reabrir Mes',
    reopening: 'Reabriendo...',
    monthsWithoutClose: 'Mes Sin Cerrar',
    monthsWithoutClosePlural: 'Meses Sin Cerrar',
    open: 'ABIERTO',
    settleHere: 'Liquidar aquí',
    viewAndClose: 'Ver y cerrar',
    andMore: 'y',
    moreMonths: 'mes más sin cerrar',
    moreMonthsPlural: 'meses más sin cerrar',
    income: 'Ingresos',
    fixedExpenses: 'Gastos Fijos',
    commissions: 'Comisiones',
    netProfit: 'Saldo Neto',
    paymentMethods: '💳 Ingresos por Método de Pago',
    cashLabel: '💵 Efectivo',
    bankNet: '🏦 Banco neto',
    ofTotal: 'del total',
    gross: 'Bruto',
    commission2: 'Comisión',
    incomeByBarber: '💈 Ingresos por Barbero',
    totalServices: 'Total servicios',
    paid: 'Ya pagado',
    pending: 'Pendiente',
    incomeDist: '🍕 Distribución de Ingresos por Barbero',
    monthExpenses: '📋 Gastos del Mes',
    date: 'Fecha',
    detail: 'Detalle',
    amount: 'Monto',
    noExpensesMonth: 'Sin gastos registrados en este mes',
    cashFundTitle: '💵 Fondo de Caja',
    currentFundBalance: 'Saldo Actual del Fondo',
    fundMovements: 'Movimientos de',
    fundInflows: '➕ Ingresos al fondo',
    fundOutflows: '➖ Egresos del fondo',
    partnerBalances: '🤝 Saldos de Socios / Dueños',
    utilityPercent: '% de la utilidad',
    owesBarberShop: '⚠️ Debe a la barbería',
    pendingCollection: '💰 Pendiente de cobro',
    settled: '✅ Saldado',
    monthBenefit: 'Beneficio mes',
    alreadyCollected: 'Ya cobrado',
    mustReturn: 'Debe devolver',
    overchargedWarning: 'Este socio cobró',
    overchargedWarning2: 'más de lo correspondiente. Registrá una "Devolución" en Inicio.',
    partnerDistribution: '💰 Reparto de Socios',
    assignedAmount: 'Monto asignado:',
    totalPaid: 'Total pagado:',
    missingToPay: 'Falta pagar:',
    owesShop: 'Debe a la barbería:',
    paymentDetail: 'Detalle de pagos',
    noPaymentsMonth: 'Sin pagos registrados este mes',
    dailyEvolution: '📅 Evolución Diaria',
    incomeLabel: 'Ingresos',
    expensesLabel: 'Gastos',
    day: 'Día',
    annualComparison: '📊 Comparativo Interanual',
    year: 'Año',
    expensesByCategory: '🍕 Gastos por Categoría',
    exportReport: 'Exportar Reporte de',
    exportTitle: 'Exportar Reporte',
    excelCSV: 'Excel (CSV)',
    excelSubtitle: 'Datos tabulares listos para abrir en Excel',
    printPDF: 'Imprimir / PDF',
    printSubtitle: 'Abre el diálogo de impresión del navegador',
    imagePNG: 'Imagen (PNG)',
    imageSubtitle: 'Resumen visual listo para compartir',
    closeMonth: 'Cerrar Mes',
    closeHistoryTitle: '📋 Historial de Cierres',
    utility: 'Utilidad:',
    closedBadge: 'Cerrado',
    openBadge: 'Abierto',
    // Modal cerrar mes
    closeMonthTitle: 'Cerrar',
    closeMonthWarning: 'Esta acción bloqueará el mes y no podrá editarse. Se enviará una copia de seguridad a Google Drive automáticamente.',
    totalIncome: 'Ingresos Totales',
    fixedExpenses2: 'Gastos Fijos',
    netUtility: 'Utilidad Neta',
    confirmClose: 'Confirmar Cierre de Mes',
    closing: 'Cerrando...',
    monthClosedOk: '¡Mes cerrado correctamente!',
    backupSentDrive: 'Copia de seguridad enviada a Drive',
    // Modal liquidación rápida
    quickSettlement: '💸 Liquidación Rápida',
    loadingPending: 'Cargando pendientes...',
    allPaid: '¡Todo pagado!',
    allPaidSubtitle: 'Ya podés cerrar el mes desde el panel.',
    cashAvailable: '💵 Efectivo disponible en caja',
    barbersPending: '💈 Barberos con saldo pendiente',
    partnersPending: '🤝 Socios con saldo pendiente',
    benefit: 'Beneficio',
    generated2: 'Generado',
    amountToPay: 'Monto a pagar',
    pay: 'Pagar',
    paying: '...',
    conceptPlaceholderBarber: 'Concepto (ej: Pago comisión mayo)',
    conceptPlaceholderPartner: 'Concepto (ej: Pago utilidad mayo)',
    settlementTip: '💡 Una vez pagados todos los saldos, cerrá el mes desde el Panel para bloquearlo.',
    // ScreenInicio etiquetas adicionales
    filterDateLabel: 'Fecha',
    incomeLabel2: '💰 Ingresos',
    expensesLabel2: '📋 Gastos',
    advancesLabel: '💳 Adelantos',
    partners: 'Socios',
    barbers: 'Barberos',
    noPays: 'Sin pagos',
    total: 'Total',
    cashInBoxLabel: '💵 Efectivo en Caja',
    cashDayFund: 'Efectivo día + Fondo',
    netBalanceLabel: '📊 Saldo Neto',
    incomeMinusCom: 'Ingresos − Com. − Gastos − Pagos',
    quickRegisterTitle: 'Registro Rápido',
    monthClosedAlert: 'El mes está cerrado.',
    monthlyClosed: 'El mes está <strong>cerrado</strong>. Reabrilo en el Panel para agregar registros.',
    registerSaleBtn: 'Registrar Venta',
    cashAuditBtn: '📊 Arqueo / Cerrar Caja del Día',
    noRecordsDate: 'Sin registros en esta fecha',
    salesDay: '💈 Ventas del día',
    expensesDay: '📋 Gastos del día',
    advancesDay: '💳 Adelantos / Pagos',
    auditApplied: '✓ Arqueo aplicado',
    cash2: 'Efectivo',
    bank2: 'Banco',
    cashAudit2: '(arqueo)',
    fund: '🏦 Fondo',
    // Otros
    version: 'Versión',
    localSystem: '100% local · Sin servidor · Sin costo',
  },
  en: {
    appearance: 'Appearance & Language',
    theme: 'Theme',
    darkMode: 'Dark',
    lightMode: 'Light',
    language: 'Language',
    settings: 'Settings',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    loading: 'Loading...',
    success: 'Saved successfully',
    error: 'An error occurred',
    navHome: 'Home',
    navBarbers: 'Barbers',
    navPanel: 'Panel',
    navSettings: 'Settings',
    myBarberShop: 'My Barber Shop',
    administration: 'Administration',
    configNameLogo: 'Configure Name & Logo',
    managePartners: 'Manage Partners',
    securityAccess: 'Security & Access',
    currencyCommission: 'Currency & Bank Commission',
    manageBarbers: 'Manage Barbers',
    manageServices: 'Manage Services & Products',
    cashFund: 'Cash Fund (Change)',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    activate: 'Activate',
    pause: 'Pause',
    saveChanges: 'Save Changes',
    addNew: 'Add New',
    registerSale: 'Register Sale',
    advancePayment: 'Advance / Payment',
    cashAudit: 'Cash Audit / Close Day',
    quickRegister: 'Quick Register',
    todaySales: "Today's Sales",
    monthClosed: 'This month is closed. Reopen it in the Panel to add records.',
    registerSaleTitle: 'Register Sale',
    registerExpenseTitle: 'Register Expense',
    advanceTitle: 'Advance / Payment',
    cashAuditTitle: 'Cash Audit',
    myBarberShopSection: 'My Barber Shop',
    administrationSection: 'Administration',
    configNameLogoBtn: 'Configure Name & Logo',
    manageSociosBtn: 'Manage Partners',
    securityAccessBtn: 'Security & Access',
    currencyCommissionBtn: 'Currency & Bank Commission',
    manageBarbersBtn: 'Manage Barbers',
    manageServicesBtn: 'Manage Services & Products',
    cashFundBtn: 'Cash Fund (Change)',
    filterDate: 'Filtering by date',
    today: 'Today',
    totalSales: 'Total Sales',
    cash: 'Cash',
    bank: 'Bank',
    bankCommission: 'Bank Commission',
    barberCommissions: 'Barber Commissions',
    partnerPayments: 'Partner Payments',
    netBalance: 'Net Balance',
    cashInBox: 'Cash in Box',
    cashFundLabel: 'Cash Fund',
    expenses: 'Expenses',
    noSalesDay: 'No sales this day',
    month_0: 'January', month_1: 'February', month_2: 'March', month_3: 'April',
    month_4: 'May', month_5: 'June', month_6: 'July', month_7: 'August',
    month_8: 'September', month_9: 'October', month_10: 'November', month_11: 'December',
    barbersTitle: 'Barbers',
    currentMonth: 'Current',
    goToCurrentMonth: '📅 Go to current month',
    noActiveBarbers: 'No active barbers',
    noActivityMonth: 'No activity in',
    active: '● Active',
    inactive: '● Inactive',
    generated: 'Generated (month)',
    grossCommission: 'Gross Commission',
    advancesPaid: 'Advances paid',
    netBalance2: 'Net balance',
    commissionGenMinusAdv: 'Commission generated minus advances paid',
    advanceExceedsComm: 'Advance minus commission generated',
    canStillCollect: '✓ Can still collect',
    advanceExceedsBy: '⚠️ Advance exceeds commission by',
    zeroBalance: '✓ Zero balance',
    advanceHistory: '💸 Advance / Payment History',
    noAdvancesMonth: 'No advances registered this month.',
    productsNoBenefit: 'Product sales generate no commission — 100% goes to the shop',
    newBarber: 'New Barber',
    barberAdded: 'Barber added!',
    fullName: 'Full Name',
    serviceCommission: 'Service Commission',
    addBarber: 'Add Barber',
    servicesProducts: 'Services & Products',
    services: 'Services',
    products: 'Products',
    noServicesYet: 'No services yet',
    noProductsYet: 'No products yet',
    addService: 'Add service',
    addProduct: 'Add product',
    serviceName: 'Service name',
    productName: 'Product name',
    currentStock: 'Current stock',
    minStock: 'Minimum stock',
    added: '✓ Added',
    panelTitle: 'Panel',
    inProgress: '· In progress',
    monthClosed2: 'Month closed — data locked',
    reopenMonth: 'Reopen Month',
    reopening: 'Reopening...',
    monthsWithoutClose: 'Month Without Closing',
    monthsWithoutClosePlural: 'Months Without Closing',
    open: 'OPEN',
    settleHere: 'Settle here',
    viewAndClose: 'View and close',
    andMore: 'and',
    moreMonths: 'more month without closing',
    moreMonthsPlural: 'more months without closing',
    income: 'Income',
    fixedExpenses: 'Fixed Expenses',
    commissions: 'Commissions',
    netProfit: 'Net Balance',
    paymentMethods: '💳 Income by Payment Method',
    cashLabel: '💵 Cash',
    bankNet: '🏦 Net Bank',
    ofTotal: 'of total',
    gross: 'Gross',
    commission2: 'Commission',
    incomeByBarber: '💈 Income by Barber',
    totalServices: 'Total services',
    paid: 'Already paid',
    pending: 'Pending',
    incomeDist: '🍕 Income Distribution by Barber',
    monthExpenses: '📋 Month Expenses',
    date: 'Date',
    detail: 'Detail',
    amount: 'Amount',
    noExpensesMonth: 'No expenses recorded this month',
    cashFundTitle: '💵 Cash Fund',
    currentFundBalance: 'Current Fund Balance',
    fundMovements: 'Movements of',
    fundInflows: '➕ Fund inflows',
    fundOutflows: '➖ Fund outflows',
    partnerBalances: '🤝 Partner / Owner Balances',
    utilityPercent: '% of profit',
    owesBarberShop: '⚠️ Owes the shop',
    pendingCollection: '💰 Pending collection',
    settled: '✅ Settled',
    monthBenefit: 'Month benefit',
    alreadyCollected: 'Already collected',
    mustReturn: 'Must return',
    overchargedWarning: 'This partner collected',
    overchargedWarning2: 'more than their share. Register a "Return" in Home.',
    partnerDistribution: '💰 Partner Distribution',
    assignedAmount: 'Assigned amount:',
    totalPaid: 'Total paid:',
    missingToPay: 'Still to pay:',
    owesShop: 'Owes the shop:',
    paymentDetail: 'Payment detail',
    noPaymentsMonth: 'No payments recorded this month',
    dailyEvolution: '📅 Daily Evolution',
    incomeLabel: 'Income',
    expensesLabel: 'Expenses',
    day: 'Day',
    annualComparison: '📊 Annual Comparison',
    year: 'Year',
    expensesByCategory: '🍕 Expenses by Category',
    exportReport: 'Export Report for',
    exportTitle: 'Export Report',
    excelCSV: 'Excel (CSV)',
    excelSubtitle: 'Tabular data ready to open in Excel',
    printPDF: 'Print / PDF',
    printSubtitle: 'Opens the browser print dialog',
    imagePNG: 'Image (PNG)',
    imageSubtitle: 'Visual summary ready to share',
    closeMonth: 'Close Month',
    closeHistoryTitle: '📋 Closing History',
    utility: 'Profit:',
    closedBadge: 'Closed',
    openBadge: 'Open',
    closeMonthTitle: 'Close',
    closeMonthWarning: 'This action will lock the month and it cannot be edited. A backup will be sent to Google Drive automatically.',
    totalIncome: 'Total Income',
    fixedExpenses2: 'Fixed Expenses',
    netUtility: 'Net Profit',
    confirmClose: 'Confirm Month Close',
    closing: 'Closing...',
    monthClosedOk: 'Month closed successfully!',
    backupSentDrive: 'Backup sent to Drive',
    quickSettlement: '💸 Quick Settlement',
    loadingPending: 'Loading pending...',
    allPaid: 'All paid!',
    allPaidSubtitle: 'You can now close the month from the panel.',
    cashAvailable: '💵 Cash available in register',
    barbersPending: '💈 Barbers with pending balance',
    partnersPending: '🤝 Partners with pending balance',
    benefit: 'Benefit',
    generated2: 'Generated',
    amountToPay: 'Amount to pay',
    pay: 'Pay',
    paying: '...',
    conceptPlaceholderBarber: 'Concept (e.g. Commission payment May)',
    conceptPlaceholderPartner: 'Concept (e.g. Profit payment May)',
    settlementTip: '💡 Once all balances are paid, close the month from the Panel to lock it.',
    filterDateLabel: 'Date',
    incomeLabel2: '💰 Income',
    expensesLabel2: '📋 Expenses',
    advancesLabel: '💳 Advances',
    partners: 'Partners',
    barbers: 'Barbers',
    noPays: 'No payments',
    total: 'Total',
    cashInBoxLabel: '💵 Cash in Register',
    cashDayFund: 'Day cash + Fund',
    netBalanceLabel: '📊 Net Balance',
    incomeMinusCom: 'Income − Com. − Expenses − Payments',
    quickRegisterTitle: 'Quick Register',
    monthClosedAlert: 'Month is closed.',
    monthlyClosed: 'Month is <strong>closed</strong>. Reopen it in the Panel to add records.',
    registerSaleBtn: 'Register Sale',
    cashAuditBtn: '📊 Cash Audit / Close Day',
    noRecordsDate: 'No records on this date',
    salesDay: '💈 Day sales',
    expensesDay: '📋 Day expenses',
    advancesDay: '💳 Advances / Payments',
    auditApplied: '✓ Audit applied',
    cash2: 'Cash',
    bank2: 'Bank',
    cashAudit2: '(audit)',
    fund: '🏦 Fund',
    version: 'Version',
    localSystem: '100% local · No server · No cost',
  },
  pt: {
    appearance: 'Aparência e Idioma',
    theme: 'Tema',
    darkMode: 'Escuro',
    lightMode: 'Claro',
    language: 'Idioma',
    settings: 'Configurações',
    save: 'Salvar',
    cancel: 'Cancelar',
    close: 'Fechar',
    loading: 'Carregando...',
    success: 'Salvo com sucesso',
    error: 'Ocorreu um erro',
    navHome: 'Início',
    navBarbers: 'Barbeiros',
    navPanel: 'Painel',
    navSettings: 'Ajustes',
    myBarberShop: 'Minha Barbearia',
    administration: 'Administração',
    configNameLogo: 'Configurar Nome e Logo',
    managePartners: 'Gerenciar Sócios',
    securityAccess: 'Segurança e Acesso',
    currencyCommission: 'Moeda e Comissão Bancária',
    manageBarbers: 'Gerenciar Barbeiros',
    manageServices: 'Gerenciar Serviços e Produtos',
    cashFund: 'Fundo de Caixa (Troco)',
    add: 'Adicionar',
    edit: 'Editar',
    delete: 'Excluir',
    activate: 'Ativar',
    pause: 'Pausar',
    saveChanges: 'Salvar Alterações',
    addNew: 'Adicionar Novo',
    registerSale: 'Registrar Venda',
    expenses: 'Despesas',
    advancePayment: 'Adiantamento / Pagamento',
    cashAudit: 'Fechamento de Caixa',
    quickRegister: 'Registro Rápido',
    todaySales: 'Vendas do Dia',
    monthClosed: 'Este mês está fechado. Reabra no Painel para adicionar registros.',
    registerSaleTitle: 'Registrar Venda',
    registerExpenseTitle: 'Registrar Despesa',
    advanceTitle: 'Adiantamento / Pagamento',
    cashAuditTitle: 'Fechamento de Caixa',
    myBarberShopSection: 'Minha Barbearia',
    administrationSection: 'Administração',
    configNameLogoBtn: 'Configurar Nome e Logo',
    manageSociosBtn: 'Gerenciar Sócios',
    securityAccessBtn: 'Segurança e Acesso',
    currencyCommissionBtn: 'Moeda e Comissão Bancária',
    manageBarbersBtn: 'Gerenciar Barbeiros',
    manageServicesBtn: 'Gerenciar Serviços e Produtos',
    cashFundBtn: 'Fundo de Caixa (Troco)',
    filterDate: 'Filtrando por data',
    today: 'Hoje',
    totalSales: 'Total Vendas',
    cash: 'Dinheiro',
    bank: 'Banco',
    bankCommission: 'Comissão Bancária',
    barberCommissions: 'Comissões Barbeiros',
    partnerPayments: 'Pagamentos Sócios',
    netBalance: 'Saldo Líquido',
    cashInBox: 'Dinheiro no Caixa',
    cashFundLabel: 'Fundo de Caixa',
    noSalesDay: 'Sem vendas este dia',
    version: 'Versão',
    localSystem: '100% local · Sem servidor · Sem custo',
  },
  de: {
    appearance: 'Darstellung & Sprache',
    theme: 'Thema',
    darkMode: 'Dunkel',
    lightMode: 'Hell',
    language: 'Sprache',
    settings: 'Einstellungen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    loading: 'Lädt...',
    success: 'Erfolgreich gespeichert',
    error: 'Ein Fehler ist aufgetreten',
    navHome: 'Start',
    navBarbers: 'Friseure',
    navPanel: 'Panel',
    navSettings: 'Einstellungen',
    myBarberShop: 'Mein Friseursalon',
    administration: 'Verwaltung',
    configNameLogo: 'Name & Logo konfigurieren',
    managePartners: 'Partner verwalten',
    securityAccess: 'Sicherheit & Zugang',
    currencyCommission: 'Währung & Bankprovision',
    manageBarbers: 'Friseure verwalten',
    manageServices: 'Dienste & Produkte verwalten',
    cashFund: 'Kassenfonds (Wechselgeld)',
    add: 'Hinzufügen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    activate: 'Aktivieren',
    pause: 'Pausieren',
    saveChanges: 'Änderungen speichern',
    addNew: 'Neu hinzufügen',
    registerSale: 'Verkauf erfassen',
    expenses: 'Ausgaben',
    advancePayment: 'Vorschuss / Zahlung',
    cashAudit: 'Kassenabschluss',
    quickRegister: 'Schnellerfassung',
    todaySales: 'Heutige Verkäufe',
    monthClosed: 'Dieser Monat ist gesperrt. Öffne ihn im Panel.',
    registerSaleTitle: 'Verkauf erfassen',
    registerExpenseTitle: 'Ausgabe erfassen',
    advanceTitle: 'Vorschuss / Zahlung',
    cashAuditTitle: 'Kassenabschluss',
    myBarberShopSection: 'Mein Friseursalon',
    administrationSection: 'Verwaltung',
    configNameLogoBtn: 'Name & Logo konfigurieren',
    manageSociosBtn: 'Partner verwalten',
    securityAccessBtn: 'Sicherheit & Zugang',
    currencyCommissionBtn: 'Währung & Bankprovision',
    manageBarbersBtn: 'Friseure verwalten',
    manageServicesBtn: 'Dienste & Produkte verwalten',
    cashFundBtn: 'Kassenfonds (Wechselgeld)',
    filterDate: 'Nach Datum filtern',
    today: 'Heute',
    totalSales: 'Gesamtumsatz',
    cash: 'Bargeld',
    bank: 'Bank',
    bankCommission: 'Bankprovision',
    barberCommissions: 'Friseurprovisionen',
    partnerPayments: 'Partnerzahlungen',
    netBalance: 'Netto-Saldo',
    cashInBox: 'Bargeld in Kasse',
    cashFundLabel: 'Kassenbestand',
    noSalesDay: 'Keine Verkäufe an diesem Tag',
    version: 'Version',
    localSystem: '100% lokal · Kein Server · Keine Kosten',
  },
  fr: {
    appearance: 'Apparence & Langue',
    theme: 'Thème',
    darkMode: 'Sombre',
    lightMode: 'Clair',
    language: 'Langue',
    settings: 'Paramètres',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    loading: 'Chargement...',
    success: 'Enregistré avec succès',
    error: 'Une erreur est survenue',
    navHome: 'Accueil',
    navBarbers: 'Coiffeurs',
    navPanel: 'Tableau',
    navSettings: 'Paramètres',
    myBarberShop: 'Mon Salon',
    administration: 'Administration',
    configNameLogo: 'Configurer Nom & Logo',
    managePartners: 'Gérer les Associés',
    securityAccess: 'Sécurité & Accès',
    currencyCommission: 'Devise & Commission Bancaire',
    manageBarbers: 'Gérer les Coiffeurs',
    manageServices: 'Gérer les Services & Produits',
    cashFund: 'Fonds de Caisse (Monnaie)',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    activate: 'Activer',
    pause: 'Mettre en pause',
    saveChanges: 'Enregistrer les modifications',
    addNew: 'Ajouter nouveau',
    registerSale: 'Enregistrer une vente',
    expenses: 'Dépenses',
    advancePayment: 'Avance / Paiement',
    cashAudit: 'Clôture de caisse',
    quickRegister: 'Enregistrement rapide',
    todaySales: "Ventes d'aujourd'hui",
    monthClosed: 'Ce mois est clôturé. Rouvrez-le dans le Panel.',
    registerSaleTitle: 'Enregistrer une vente',
    registerExpenseTitle: 'Enregistrer une dépense',
    advanceTitle: 'Avance / Paiement',
    cashAuditTitle: 'Clôture de caisse',
    myBarberShopSection: 'Mon Salon',
    administrationSection: 'Administration',
    configNameLogoBtn: 'Configurer Nom & Logo',
    manageSociosBtn: 'Gérer les Associés',
    securityAccessBtn: 'Sécurité & Accès',
    currencyCommissionBtn: 'Devise & Commission Bancaire',
    manageBarbersBtn: 'Gérer les Coiffeurs',
    manageServicesBtn: 'Gérer les Services & Produits',
    cashFundBtn: 'Fonds de Caisse (Monnaie)',
    filterDate: 'Filtrer par date',
    today: "Aujourd'hui",
    totalSales: 'Ventes Totales',
    cash: 'Espèces',
    bank: 'Banque',
    bankCommission: 'Commission Bancaire',
    barberCommissions: 'Commissions Coiffeurs',
    partnerPayments: 'Paiements Associés',
    netBalance: 'Solde Net',
    cashInBox: 'Espèces en Caisse',
    cashFundLabel: 'Fonds de Caisse',
    noSalesDay: 'Aucune vente ce jour',
    version: 'Version',
    localSystem: '100% local · Sans serveur · Sans frais',
  },
  ar: {
    appearance: 'المظهر واللغة',
    theme: 'المظهر',
    darkMode: 'داكن',
    lightMode: 'فاتح',
    language: 'اللغة',
    settings: 'الإعدادات',
    save: 'حفظ',
    cancel: 'إلغاء',
    close: 'إغلاق',
    loading: 'جارٍ التحميل...',
    success: 'تم الحفظ بنجاح',
    error: 'حدث خطأ',
    navHome: 'الرئيسية',
    navBarbers: 'الحلاقون',
    navPanel: 'لوحة',
    navSettings: 'الإعدادات',
    myBarberShop: 'صالوني',
    administration: 'الإدارة',
    configNameLogo: 'إعداد الاسم والشعار',
    managePartners: 'إدارة الشركاء',
    securityAccess: 'الأمان والوصول',
    currencyCommission: 'العملة وعمولة البنك',
    manageBarbers: 'إدارة الحلاقين',
    manageServices: 'إدارة الخدمات والمنتجات',
    cashFund: 'صندوق النقد (الفكة)',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    activate: 'تفعيل',
    pause: 'إيقاف مؤقت',
    saveChanges: 'حفظ التغييرات',
    addNew: 'إضافة جديد',
    registerSale: 'تسجيل بيع',
    expenses: 'المصروفات',
    advancePayment: 'سلفة / دفعة',
    cashAudit: 'جرد الصندوق',
    quickRegister: 'تسجيل سريع',
    todaySales: 'مبيعات اليوم',
    monthClosed: 'هذا الشهر مغلق. أعد فتحه من اللوحة لإضافة سجلات.',
    registerSaleTitle: 'تسجيل بيع',
    registerExpenseTitle: 'تسجيل مصروف',
    advanceTitle: 'سلفة / دفعة',
    cashAuditTitle: 'جرد الصندوق',
    myBarberShopSection: 'صالوني',
    administrationSection: 'الإدارة',
    configNameLogoBtn: 'إعداد الاسم والشعار',
    manageSociosBtn: 'إدارة الشركاء',
    securityAccessBtn: 'الأمان والوصول',
    currencyCommissionBtn: 'العملة وعمولة البنك',
    manageBarbersBtn: 'إدارة الحلاقين',
    manageServicesBtn: 'إدارة الخدمات والمنتجات',
    cashFundBtn: 'صندوق النقد (الفكة)',
    filterDate: 'تصفية حسب التاريخ',
    today: 'اليوم',
    totalSales: 'إجمالي المبيعات',
    cash: 'نقدًا',
    bank: 'البنك',
    bankCommission: 'عمولة البنك',
    barberCommissions: 'عمولات الحلاقين',
    partnerPayments: 'مدفوعات الشركاء',
    netBalance: 'الرصيد الصافي',
    cashInBox: 'النقد في الصندوق',
    cashFundLabel: 'رأس مال الصندوق',
    noSalesDay: 'لا توجد مبيعات في هذا اليوم',
    version: 'الإصدار',
    localSystem: 'محلي 100٪ · بدون خادم · بدون تكلفة',
  },
}